### ISSUE TITLE
Remember to support *.gemspec files in Ruby-on-Rails projects

### ISSUE THREAD

**Issue by jasnow** [G-Rath/osv-detector#168]
Remember to support *.gemspec files in Ruby-on-Rails projects. Many times you find these instead of Gemfile file.

**Comment by G-Rath** [comment]
I have thought about this, but the problem is that `gemspec` files are native Ruby so in addition to even just having to parse Ruby (which is a syntactically complex language), you have to account for the behaviour at runtime because you can have conditions (though I'm not sure if there is a realworld usecase for doing that in a gemspec file for listing a dependency).

The `gemspec` file also generally represents dependency constraints rather than exact versions - meaning you're probably not going to get accurate results unless you expand those constraints into every possible version (which could be all versions, and the detector doesn't know how to do this because that would require interacting with gem repos specifically).

Obviously right now an easy way to resolve this is to have a `Gemfile` that pulls from your gemspec:

```
# frozen_string_literal: true

source 'https://rubygems.org'

gemspec
```

and then check the resulting `Gemfile.lock` - personally I don't think that should be a problem, but if people really don't like having both a gemspec & `Gemfile`, then maybe a good middleground could be to have a Ruby script that generates [a CSV for the detector](https://github.com/G-Rath/osv-detector#passing-arbitrary-package-details-advanced-usage) based on the gemspec; that way you could use Bundler to expand the constraints (iirc there's even a method or two dedicated to this)

**Comment by jasnow** [comment]
Thanks for nice response. You can close or keep around as a reminder.

**Comment by jasnow** [comment]
pruning
