### ISSUE TITLE
Support for non-rubygems vulnerabilities

### ISSUE THREAD

**Issue by jasnow** [G-Rath/osv-detector#184]
Appears that you get rubygem vulnerabilities by way of GHSA  database feed.
Do you have support for the rubies (ruby-lang.org, jruby.org, mruby.org) languages?
Thanks.

**Comment by G-Rath** [comment]
I assume you're asking about checking the version of Ruby itself? That is not supported currently, mainly because afaik neither the osv.dev or GitHub advisory databases contain entries for Ruby - in terms of parsing, it would be trivial to have the `Gemfile.lock` parser support parsing the `RUBY VERSION` block for the actual version.

**Comment by jasnow** [comment]
Example: https://github.com/advisories/GHSA-w9fp-2996-hhwx

**Comment by G-Rath** [comment]
yeah, those exist but are not actually in the database since they're marked as [unreviewed](https://github.com/github/advisory-database/blob/94a8d29b00950ec3c2c786bde7851f97990d6ac9/advisories/unreviewed/2022/05/GHSA-w9fp-2996-hhwx/GHSA-w9fp-2996-hhwx.json) - that's because the osv spec doesn't have a way of representing things like "ruby the language/sdk" so the advisory itself has no `affected` data meaning there's nothing `osv-detector` can do (since it needs that to be able to match the advisory).

`ruby-advisory-db` is not using the OSV specification for its entries, so its not directly compatible, though they do have versions so you should write a script to create OSVs from their entries, and use that as a custom database](https://github.com/G-Rath/osv-detector#extra-databases) then passing in the Ruby version(s) as a [as a CSV](https://github.com/G-Rath/osv-detector#passing-arbitrary-package-details-advanced-usage) (I've been playing with something similar for doing end-of-life checks).

**Comment by jasnow** [comment]
> Example: [GHSA-w9fp-2996-hhwx](https://github.com/advisories/GHSA-w9fp-2996-hhwx)

I tried to review them but they do not have a required "ecosystem" value for non-rubygems. Go
to the bottom right corner of the above advisory and click on "improve..." and click on
"Ecosystems" to see.

I have 11 GHSA "rubygems" PRs approved or merged in the last few weeks.

**Comment by G-Rath** [comment]
In that case those advisories will be reported by `osv-detector` - the exception is advisories for Ruby itself since that isn't a gem; if you have gotten an advisory for a Ruby SDK reviewed then I think it would make sense for `osv-detector` to start parsing the Ruby version from `Gemfile.lock` and include it as a "package" in its output (at least until the OSV spec decides how to handle those kind of vulnerabilities)

**Comment by jasnow** [comment]
Also found a few GHSA adversaries that were just ruby application code and pointed to a specific repo to demo it.

**Comment by jasnow** [comment]
Duplicated issue on osv-schema repo: https://github.com/ossf/osv-schema/issues/123

**Comment by jasnow** [comment]
Move this issue to osv-schecma repo: https://github.com/ossf/osv-schema/issues/123
